### ISSUE TITLE
Add more balance to homepage

### ISSUE THREAD

**Issue by christofferengstrom** [agensdev/WomansHealth#1]
<img width="380" alt="screen shot 2017-04-04 at 13 55 11" src="https://cloud.githubusercontent.com/assets/5484536/24655386/5b0998cc-193e-11e7-979b-ad41fe30f270.png">
This is my suggestion to adjusted home screen. I didn't have your colors and icons, so I just made some new ones based on Googles guidelines. If you want assets and colors you have access to them here:

[Link to inVision](https://projects.invisionapp.com/d/main#/console/10710845/227257503/inspect)

- [x] Change tiles to give a better sense of balanse to the page.
1: 50% height, 100% width
2: 25% height, 100% width
3,4,5: 25% height, 33% width

- [x] Consistency on icon / label placement.

- [x] Add tap state tiles. To give the user quick response that the element is interactive and the app is responding.

**Comment by hfossli** [comment]
I just took a screenshot on a nexus 5x 🎉  Maybe adjust the position of icons and text slightly in the y-axis?

![screenshot_1491563689](https://cloud.githubusercontent.com/assets/3652587/24798066/666d2b22-1b94-11e7-86d8-1c492c1c2cc4.png)

**Comment by blashca** [comment]
Yep! It surely needed fixing. I've checked on several screen sizes and it looks good now :)

**Comment by hfossli** [comment]
Since it is merged we can close this now. If you want further changes @christofferengstrom then create a new issue.
