### ISSUE TITLE
Medical Appointment - Don't mix upcoming appointments with suggested appointments

### ISSUE THREAD

**Issue by christofferengstrom** [agensdev/WomansHealth#2]
![appointments](https://cloud.githubusercontent.com/assets/5484536/24694398/fa751104-19e1-11e7-9b7b-4ff17e4be048.png)

[Link to project in inVision](https://projects.invisionapp.com/d/main#/projects/prototypes/10710845)

- [x] No upcoming appointments --> Show a fallback screen with some kind of text helping the user understand the page and the next step.

- [x] List upcoming appointments when user has 1 or more planned.

**Comment by blashca** [comment]
It was a good idea to separate these two :)

**Comment by hfossli** [comment]
After creating an appointment I would like to return to the list named "Medical appointments" and not the list named "Choose type". 

Because
1. I get a final confirmation that the entry is saved and registered
2. It is confusing to register a new appointment without first tapping the circle +

**Comment by blashca** [comment]
Good thinking 👍 I've added commit to #6 covering this.

**Comment by hfossli** [comment]
Yep. That solved some confusion indeed. :)

**Comment by blashca** [comment]
Do you think we can close this one?

**Comment by hfossli** [comment]
I just had a chat with @christofferengstrom, he has some final QA input. :)

**Comment by christofferengstrom** [comment]
# QA suggestions

![scrollview](https://cloud.githubusercontent.com/assets/5484536/25239796/63ea1f92-25f1-11e7-9d3c-c549b19d9f5a.png)

- [ ] Move the subheader into the scrollview. I don't think it needs to be fixed. Fixed items needs to have a good reason to be fixed. This type of objects should scroll out of the screen together with te rest of the view.

### UI adjustments to list item. 
Now the dividers is very dominant and takes fokus away from the title of each list item.

![list item](https://cloud.githubusercontent.com/assets/5484536/25240758/f98bcde6-25f3-11e7-8e95-4382a72478a3.png)

- [ ] 1. Double check that divider is only 1dp
- [ ] 1. Change color on divider to lighter grey --> #E6E6E6
- [ ] 2. Change color on "List item title" to darker grey --> #333333
- [ ] 3. Looks like list item is missing padding right

The same goes for appointment list items if that's a separate component.

**Comment by blashca** [comment]
I think we can close this after merging PR #8.

**Comment by hfossli** [comment]
Great! All concerns have been adressed!

**Comment by christofferengstrom** [comment]
👍  Looks much better now!
