### ISSUE TITLE
Add option to fill in appointment details from phone contacts

### ISSUE THREAD

**Issue by Ehyeh-Asher-Ehyeh** [agensdev/WomansHealth#4]
When making or editing an appointment reminder, the user should have the option to select a contact from their phone's contact list and have those of name/address/phone number/email that are stored on the contact filled in automatically for the appointment.

* This requires android.permission.READ_CONTACTS permission
* App should wait to ask for permission until user first selects "Add from contacts"

(see https://developer.android.com/training/permissions/requesting.html)

**Comment by christofferengstrom** [comment]
![screen shot 2017-04-24 at 11 26 26](https://cloud.githubusercontent.com/assets/5484536/25330731/f28258c2-28e0-11e7-82d7-37901e805515.png)

- [ ] Add a button that triggers standard contacts app.

**Comment by blashca** [comment]
I've opened #9 solving this.

**Comment by blashca** [comment]
Since #9 is merged, I think we could close this one :)

**Comment by hfossli** [comment]
I think maybe it would be better if you added the title "Who is your doctor?". What do you think?

**Comment by hfossli** [comment]
Other than that this is great!

**Comment by blashca** [comment]
Yep, the title would be good. I've added it in PR #10.

**Comment by hfossli** [comment]
Great. It is more clear what is expected of the user now. I think a natural next step would be to redesign the "deatils" view, but that's out of scope for now.

**Comment by blashca** [comment]
Yes, I agree, it needs some more work on that 👍

**Comment by christofferengstrom** [comment]
The flow is a lot better now! Works as expected to add from contacts. 👍

**Comment by blashca** [comment]
![purrrfect](https://cloud.githubusercontent.com/assets/9930565/25428718/e3e0e4f4-2a76-11e7-88e0-9169859f9648.jpg)
Should we close? :)

**Comment by hfossli** [comment]
![https://media.giphy.com/media/10ERZqYioLWJ6U/giphy.gif](https://media.giphy.com/media/10ERZqYioLWJ6U/giphy.gif)
